parameters:
  hostname: hydrogen.worker.simplytestable.com
  core_url: http://app.simplytestable.com
  engines:
    html-validation:
      class: SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver      
      task-types:
        - "HTML validation"
  
glit_resque:
  prefix: "SimplyTestable\WorkerBundle"