SimplyTestableWorkerBundle_verify:
    path:  /verify/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\VerifyController::indexAction, _format: json }

SimplyTestableWorkerBundle_task_create_collection:
    path:  /task/create/collection/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\TaskController::createCollectionAction, _format: json }

SimplyTestableWorkerBundle_task_cancel:
    path:  /task/cancel/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\TaskController::cancelAction, _format: json }

SimplyTestableWorkerBundle_task_cancel_collection:
    path:  /task/cancel/collection/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\TaskController::cancelCollectionAction, _format: json }

SimplyTestableWorkerBundle_status:
    path:  /status/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\StatusController::indexAction, _format: json }

SimplyTestableWorkerBundle_default:
    path:  /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: SimplyTestableWorkerBundle_status
        permanent: true

SimplyTestableWorkerBundle_disable_readonly:
    path: /maintenance/disable-read-only/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\MaintenanceController::disableReadOnlyAction, _format: json }

SimplyTestableWorkerBundle_enable_readonly:
    path: /maintenance/enable-read-only/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\MaintenanceController::enableReadOnlyAction, _format: json }

SimplyTestableWorkerBundle_task_perform_enqueue:
    path: /maintenance/task-perform-enqueue/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\MaintenanceController::taskPerformEnqueueAction, _format: json }

SimplyTestableWorkerBundle_leave_readonly:
    path: /maintenance/leave-read-only/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\MaintenanceController::leaveReadOnlyAction, _format: json }

tasks_notify:
    path: /tasks/notify/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\TasksController::notifyAction }