status:
    path:  /
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\StatusController::indexAction }

verify:
    path:  /verify/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\VerifyController::indexAction }

task_create_collection:
    path:  /task/create/collection/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\TaskController::createCollectionAction }

task_cancel:
    path:  /task/cancel/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\TaskController::cancelAction }

task_cancel_collection:
    path:  /task/cancel/collection/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\TaskController::cancelCollectionAction }

disable_readonly:
    path: /maintenance/disable-read-only/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\MaintenanceController::disableReadOnlyAction }

enable_readonly:
    path: /maintenance/enable-read-only/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\MaintenanceController::enableReadOnlyAction }

leave_readonly:
    path: /maintenance/leave-read-only/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\MaintenanceController::leaveReadOnlyAction }

task_perform_enqueue:
    path: /maintenance/task-perform-enqueue/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\MaintenanceController::taskPerformEnqueueAction }

tasks_notify:
    path: /tasks/notify/
    defaults: { _controller: SimplyTestable\WorkerBundle\Controller\TasksController::notifyAction }
