SimplyTestableWorkerBundle_verify:
    path:  /verify/
    defaults: { _controller: SimplyTestableWorkerBundle:Verify:index, _format: json }

SimplyTestableWorkerBundle_task_create:
    path:  /task/create/
    defaults: { _controller: SimplyTestableWorkerBundle:Task:create, _format: json }

SimplyTestableWorkerBundle_task_create_collection:
    path:  /task/create/collection/
    defaults: { _controller: SimplyTestableWorkerBundle:Task:createCollection, _format: json }

SimplyTestableWorkerBundle_task_cancel:
    path:  /task/cancel/
    defaults: { _controller: SimplyTestableWorkerBundle:Task:cancel, _format: json }

SimplyTestableWorkerBundle_task_cancel_collection:
    path:  /task/cancel/collection/
    defaults: { _controller: SimplyTestableWorkerBundle:Task:cancelCollection, _format: json }

SimplyTestableWorkerBundle_status:
    path:  /status/
    defaults: { _controller: SimplyTestableWorkerBundle:Status:index, _format: json }

SimplyTestableWorkerBundle_default:
    path:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: SimplyTestableWorkerBundle_status
        permanent: true

SimplyTestableWorkerBundle_disable_readonly:
    path: /maintenance/disable-read-only/
    defaults: { _controller: SimplyTestableWorkerBundle:Maintenance:disableReadOnly, _format: json }

SimplyTestableWorkerBundle_enable_readonly:
    path: /maintenance/enable-read-only/
    defaults: { _controller: SimplyTestableWorkerBundle:Maintenance:enableReadOnly, _format: json }

SimplyTestableWorkerBundle_task_perform_enqueue:
    path: /maintenance/task-perform-enqueue/
    defaults: { _controller: SimplyTestableWorkerBundle:Maintenance:taskPerformEnqueue, _format: json }

SimplyTestableWorkerBundle_leave_readonly:
    path: /maintenance/leave-read-only/
    defaults: { _controller: SimplyTestableWorkerBundle:Maintenance:leaveReadOnly, _format: json }

tasks_notify:
    path: /tasks/notify/
    defaults: { _controller: SimplyTestableWorkerBundle:Tasks:notify }