SimplyTestableWorkerBundle_verify:
    pattern:  /verify/
    defaults: { _controller: SimplyTestableWorkerBundle:Verify:index, _format: json }   
    
SimplyTestableWorkerBundle_task_create:
    pattern:  /task/create/
    defaults: { _controller: SimplyTestableWorkerBundle:Task:create, _format: json }       
    
SimplyTestableWorkerBundle_task_cancel:
    pattern:  /task/cancel/
    defaults: { _controller: SimplyTestableWorkerBundle:Task:cancel, _format: json }
    
SimplyTestableWorkerBundle_task_cancel_collection:
    pattern:  /task/cancel/collection/
    defaults: { _controller: SimplyTestableWorkerBundle:Task:cancelCollection, _format: json }    
    
SimplyTestableWorkerBundle_status:
    pattern:  /status/
    defaults: { _controller: SimplyTestableWorkerBundle:Status:index, _format: json }    

SimplyTestableWorkerBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SimplyTestableWorkerBundle:Default:index }
