SimplyTestableWorkerBundle_verify:
    pattern:  /verify/
    defaults: { _controller: SimplyTestableWorkerBundle:Verify:index, _format: json }   

SimplyTestableWorkerBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SimplyTestableWorkerBundle:Default:index }
