services:
  SimplyTestable\WorkerBundle\Services\ResourceLocator:
      public: true
      arguments:
        - '@kernel'

  SimplyTestable\WorkerBundle\Services\MemcachedService:
      public: true

  SimplyTestable\WorkerBundle\Services\Resque\QueueService:
      public: true
      arguments:
        - '@resque'
        - '@logger'
        - '@SimplyTestable\WorkerBundle\Services\Resque\JobFactory'
