services:
  simplytestable.services.httpClientService:
    class:  SimplyTestable\WorkerBundle\Services\HttpClientService
    arguments:
        memcacheService: "@simplytestable.services.memcacheService"
        curlOptions: %curl_options%

  simplytestable.services.webResourceServiceConfiguration:
    class:  webignition\WebResource\Service\Configuration
    arguments:
        configurationValues:
          allow-uknown-resource-types: true
          retry-with-url-encoding-disabled: true
          content-type-web-resource-map: %content_type_web_resource_map%

  simplytestable.services.webResourceService:
    class:  webignition\WebResource\Service\Service
    calls:
      - [setConfiguration, [@simplytestable.services.webResourceServiceConfiguration]]

  simplytestable.services.htmlValidatorWrapperService:
    class:  webignition\HtmlValidator\Wrapper\Wrapper

  simplytestable.services.cssValidatorWrapperService:
    class:  webignition\CssValidatorWrapper\Wrapper

  simplytestable.services.nodeJslintWrapperService:
    class:  webignition\NodeJslint\Wrapper\Wrapper

  simplytestable.services.coreApplicationService:
    class:  SimplyTestable\WorkerBundle\Services\CoreApplicationService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"

  simplytestable.services.stateservice:
    class:  SimplyTestable\WorkerBundle\Services\StateService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"

  simplytestable.services.workerService:
    class:  SimplyTestable\WorkerBundle\Services\WorkerService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"
        logger: "@logger"
        salt: %secret%
        hostname: %hostname%
        coreApplicationBaseUrl: "%core_url%"
        stateService: "@simplytestable.services.stateservice"
        httpClientService: "@simplytestable.services.httpClientService"
        urlService: "@simplytestable.services.urlService"

  simplytestable.services.urlService:
    class:  SimplyTestable\WorkerBundle\Services\UrlService

  simplytestable.controller.action_listener:
    class: SimplyTestable\WorkerBundle\EventListener\BeforeListener
    arguments:
        logger: "@logger"
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  simplytestable.services.taskservice:
    class:   SimplyTestable\WorkerBundle\Services\TaskService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"
        logger: "@logger"
        stateService: "@simplytestable.services.stateservice"
        urlService: "@simplytestable.services.urlservice"
        coreApplicationService: "@simplytestable.services.coreapplicationservice"
        workerService: "@simplytestable.services.workerservice"
        httpClientService: "@simplytestable.services.httpClientService"
    calls:
      - [addTaskDriver, ['html validation', "@simplytestable.services.taskdriver.htmlvalidation"]]
      - [addTaskDriver, ['css validation', "@simplytestable.services.taskdriver.cssvalidation"]]
      - [addTaskDriver, ['js static analysis', "@simplytestable.services.taskdriver.jslint"]]
      - [addTaskDriver, ['link integrity', "@simplytestable.services.taskdriver.linkintegrity"]]
      - [addTaskDriver, ['url discovery', "@simplytestable.services.taskdriver.urldiscovery"]]

  simplytestable.services.tasktypeservice:
    class:   SimplyTestable\WorkerBundle\Services\TaskTypeService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"

  simplytestable.services.taskdriver.htmlvalidation:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver
    arguments:
        httpClientService: "@simplytestable.services.httpclientservice"
        webResourceService: "@simplytestable.services.webResourceService"
        htmlValidatorWrapper: "@simplytestable.services.htmlValidatorWrapperService"
        stateService: "@simplytestable.services.stateService"
        validatorPath: %html-validator-path%

  simplytestable.services.taskdriver.cssvalidation:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver
    arguments:
        httpClientService: "@simplytestable.services.httpclientservice"
        webResourceService: "@simplytestable.services.webResourceService"
        cssValidatorWrapper: "@simplytestable.services.cssValidatorWrapperService"
        serializer: "@jms_serializer"
        stateService: "@simplytestable.services.stateService"
        cssValidatorJarPath: %css-validator-jar-path%

  simplytestable.services.taskdriver.jslint:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\JsLintTaskDriver
    arguments:
        httpClientService: "@simplytestable.services.httpclientservice"
        webResourceService: "@simplytestable.services.webResourceService"
        nodeJsLintWrapper: "@simplytestable.services.nodeJslintWrapperService"
        stateService: "@simplytestable.services.stateService"
        logger: "@logger"
        nodePath: %node-path%
        nodeJsLintPath: %node-jslint-path%

  simplytestable.services.taskdriver.linkintegrity:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\LinkIntegrityTaskDriver
    arguments:
        httpClientService: "@simplytestable.services.httpclientservice"
        webResourceService: "@simplytestable.services.webResourceService"
        stateService: "@simplytestable.services.stateService"
        userAgents: %link-integrity-user-agents%

  simplytestable.services.taskdriver.urldiscovery:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\UrlDiscoveryTaskDriver
    arguments:
        httpClientService: "@simplytestable.services.httpclientservice"
        webResourceService: "@simplytestable.services.webResourceService"
        stateService: "@simplytestable.services.stateService"

  simplytestable.services.resque.queueService:
    class:   SimplyTestable\WorkerBundle\Services\Resque\QueueService
    arguments:
      resque: "@bcc_resque.resque"
      environment: "%kernel.environment%"
      logger: "@logger"
      jobFactoryService: "@simplytestable.services.resque.jobFactoryService"

  simplytestable.services.resque.jobFactoryService:
    class:  SimplyTestable\WorkerBundle\Services\Resque\JobFactoryService
    arguments:
      jobClassMap: "%resque-job-class-map%"

  simplytestable.services.timecachedtaskoutputservice:
    class:   SimplyTestable\WorkerBundle\Services\TimeCachedTaskOutputService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"

  simplytestable.services.commandService:
    class:   SimplyTestable\WorkerBundle\Services\CommandService
    arguments:
      container: "@service_container"

  simplytestable.services.memcacheService:
    class:   SimplyTestable\WorkerBundle\Services\MemcacheService

  simplytestable.services.tasksservice:
    class:   SimplyTestable\WorkerBundle\Services\TasksService
    arguments:
        logger: "@logger"
        urlService: "@simplytestable.services.urlservice"
        coreApplicationService: "@simplytestable.services.coreapplicationservice"
        workerService: "@simplytestable.services.workerservice"
        httpClientService: "@simplytestable.services.httpClientService"
        taskService: "@simplytestable.services.taskservice"
    calls:
      - [setWorkerProcessCount, [%worker_process_count%]]
      - [setMaxTasksRequestFactor, [%max_tasks_request_factor%]]

  simplytestable.services.request.factory.task.create:
    class:   SimplyTestable\WorkerBundle\Services\Request\Factory\Task\CreateRequestFactory
    scope: request
    arguments:
        request: "@request"
        taskTypeService: "@simplytestable.services.tasktypeservice"

  simplytestable.services.request.factory.task.createcollection:
    class:   SimplyTestable\WorkerBundle\Services\Request\Factory\Task\CreateRequestCollectionFactory
    scope: request
    arguments:
        request: "@request"
        createRequestFactory: "@simplytestable.services.request.factory.task.create"
