services:
  SimplyTestable\WorkerBundle\Command\:
      resource: '../../Command'
      public: true
      autowire: true
      autoconfigure: true
      tags: ['console.command']

  SimplyTestable\WorkerBundle\Services\ResourceLocator:
    public: true
    arguments:
      - '@kernel'

  SimplyTestable\WorkerBundle\Services\MemcachedService:
    public: true

  SimplyTestable\WorkerBundle\Services\Resque\QueueService:
    public: true
    arguments:
      - '@resque'
      - '@logger'
      - '@SimplyTestable\WorkerBundle\Services\Resque\JobFactory'

  SimplyTestable\WorkerBundle\Services\TaskTypeService:
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'

  SimplyTestable\WorkerBundle\Services\StateService:
    arguments:
      - '@doctrine.orm.entity_manager'

  SimplyTestable\WorkerBundle\Services\HttpCache:
    arguments:
      - '@SimplyTestable\WorkerBundle\Services\MemcachedService'

  SimplyTestable\WorkerBundle\Services\TaskService:
    class:   Tests\WorkerBundle\Services\TestTaskService
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@logger'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '@SimplyTestable\WorkerBundle\Services\UrlService'
        - '@SimplyTestable\WorkerBundle\Services\CoreApplicationRouter'
        - '@SimplyTestable\WorkerBundle\Services\WorkerService'
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
    calls:
      - [addTaskDriver, ['html validation', '@SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver']]
      - [addTaskDriver, ['css validation', '@SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver']]
      - [addTaskDriver, ['js static analysis', '@SimplyTestable\WorkerBundle\Services\TaskDriver\JsLintTaskDriver']]
      - [addTaskDriver, ['link integrity', '@SimplyTestable\WorkerBundle\Services\TaskDriver\LinkIntegrityTaskDriver']]
      - [addTaskDriver, ['url discovery', '@SimplyTestable\WorkerBundle\Services\TaskDriver\UrlDiscoveryTaskDriver']]

  SimplyTestable\WorkerBundle\Services\TasksService:
    class:   Tests\WorkerBundle\Services\TestTasksService
    arguments:
      - '@logger'
      - '@SimplyTestable\WorkerBundle\Services\UrlService'
      - '@SimplyTestable\WorkerBundle\Services\CoreApplicationRouter'
      - '@SimplyTestable\WorkerBundle\Services\WorkerService'
      - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
      - '@SimplyTestable\WorkerBundle\Services\TaskService'
    calls:
      - [setWorkerProcessCount, ['%worker_process_count%']]
      - [setMaxTasksRequestFactor, ['%max_tasks_request_factor%']]