services:
  simplytestable.services.httpClient:
    class:  webignition\Http\Client\Client
    
  simplytestable.services.coreApplicationService:
    class:  SimplyTestable\WorkerBundle\Services\CoreApplicationService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        
  simplytestable.services.stateservice:
    class:  SimplyTestable\WorkerBundle\Services\StateService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"         
        
  simplytestable.services.workerService:
    class:  SimplyTestable\WorkerBundle\Services\WorkerService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"
        logger: "@logger"
        salt: %secret%
        hostname: %hostname%
        coreApplicationService: "@simplytestable.services.coreApplicationService"
        stateService: "@simplytestable.services.stateservice"
        httpClient: "@simplytestable.services.httpClient"
        
       