imports:
    - { resource: services/task-drivers.yml }
#    - { resource: services/request-factories.yml }
#    - { resource: services/commands.yml }
    - { resource: services/resque-job-factory.yml }

services:
  SimplyTestable\WorkerBundle\Services\ApplicationConfigurationService:
      arguments:
        - "@=service('kernel').getRootDir()"
        - "@=service('kernel').getCacheDir()"

  SimplyTestable\WorkerBundle\Services\CoreApplicationRouter:
      arguments:
        - '%core_url%'
        - '@SimplyTestable\WorkerBundle\Services\ResourceLocator'
        - '@SimplyTestable\WorkerBundle\Services\ApplicationConfigurationService'

  SimplyTestable\WorkerBundle\Services\HttpClientService:
      arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpCache'
        - '%curl_options%'

  simplytestable.services.webresourceserviceconfiguration:
    class:  webignition\WebResource\Service\Configuration
    arguments:
        $configurationValues:
          allow-uknown-resource-types: true
          retry-with-url-encoding-disabled: true
          content-type-web-resource-map: '%content_type_web_resource_map%'

  simplytestable.services.webresourceservice:
    class:  webignition\WebResource\Service\Service
    calls:
      - [setConfiguration, ['@simplytestable.services.webresourceserviceconfiguration']]

  simplytestable.services.htmlvalidatorwrapper:
    class:  webignition\HtmlValidator\Wrapper\Wrapper

  simplytestable.services.cssvalidatorwrapper:
    class:  webignition\CssValidatorWrapper\Wrapper

  simplytestable.services.nodejslintwrapper:
    class:  webignition\NodeJslint\Wrapper\Wrapper

  SimplyTestable\WorkerBundle\Services\WorkerService:
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@logger'
        - '%secret%'
        - '%hostname%'
        - '@SimplyTestable\WorkerBundle\Services\CoreApplicationRouter'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@SimplyTestable\WorkerBundle\Services\UrlService'
#
#  simplytestable.services.urlService:
#    class:  SimplyTestable\WorkerBundle\Services\UrlService
#
  SimplyTestable\WorkerBundle\Services\TaskService:
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@logger'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '@SimplyTestable\WorkerBundle\Services\UrlService'
        - '@SimplyTestable\WorkerBundle\Services\CoreApplicationRouter'
        - '@SimplyTestable\WorkerBundle\Services\WorkerService'
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
    calls:
      - [addTaskDriver, ['html validation', '@SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver']]
      - [addTaskDriver, ['css validation', '@SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver']]
      - [addTaskDriver, ['js static analysis', '@SimplyTestable\WorkerBundle\Services\TaskDriver\JsLintTaskDriver']]
      - [addTaskDriver, ['link integrity', '@SimplyTestable\WorkerBundle\Services\TaskDriver\LinkIntegrityTaskDriver']]
      - [addTaskDriver, ['url discovery', '@SimplyTestable\WorkerBundle\Services\TaskDriver\UrlDiscoveryTaskDriver']]
#
#  simplytestable.services.tasktypeservice:
#    class:   SimplyTestable\WorkerBundle\Services\TaskTypeService
#    arguments:
#        entityManager: '@doctrine.orm.entity_manager'
#
#  simplytestable.services.resque.queueService:
#    class:   SimplyTestable\WorkerBundle\Services\Resque\QueueService
#    arguments:
#      resque: '@resque'
#      logger: '@logger'
#      jobFactory: '@simplytestable.services.resque.jobfactory'
#
#  simplytestable.services.timecachedtaskoutputservice:
#    class:   SimplyTestable\WorkerBundle\Services\TimeCachedTaskOutputService
#    arguments:
#        entityManager: '@doctrine.orm.entity_manager'
#
#
#
#  simplytestable.services.tasksservice:
#    class:   SimplyTestable\WorkerBundle\Services\TasksService
#    arguments:
#        logger: '@logger'
#        urlService: '@simplytestable.services.urlservice'
#        coreApplicationRouter: '@simplytestable.services.coreapplicationrouter'
#        workerService: '@simplytestable.services.workerservice'
#        httpClientService: '@simplytestable.services.httpClientService'
#        taskService: "@simplytestable.services.taskservice"
#    calls:
#      - [setWorkerProcessCount, ['%worker_process_count%']]
#      - [setMaxTasksRequestFactor, ['%max_tasks_request_factor%']]
#
#  simplytestable.services.coreapplicationrouter:
#    class:   SimplyTestable\WorkerBundle\Services\CoreApplicationRouter
#    arguments:
#        baseUrl: '%core_url%'
#        kernel: '@kernel'
#        cachePath: '%kernel.cache_dir%'