services:
  simplytestable.services.httpClientService:
    class:  SimplyTestable\WorkerBundle\Services\HttpClientService
    arguments:
        memcacheService: "@simplytestable.services.memcacheService"    
        
  simplytestable.services.htmlValidatorWrapperService:
    class:  webignition\HtmlValidator\Wrapper\Wrapper 
  
  simplytestable.services.coreApplicationService:
    class:  SimplyTestable\WorkerBundle\Services\CoreApplicationService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        
  simplytestable.services.stateservice:
    class:  SimplyTestable\WorkerBundle\Services\StateService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"     
        
  simplytestable.services.workerService:
    class:  SimplyTestable\WorkerBundle\Services\WorkerService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"
        logger: "@logger"
        salt: %secret%
        hostname: %hostname%
        coreApplicationService: "@simplytestable.services.coreApplicationService"
        stateService: "@simplytestable.services.stateservice"
        httpClientService: "@simplytestable.services.httpClientService"
        urlService: "@simplytestable.services.urlService"
        
  simplytestable.services.urlService:
    class:  SimplyTestable\WorkerBundle\Services\UrlService     
    
  simplytestable.services.requestservice:
    class:   SimplyTestable\WorkerBundle\Services\RequestService    
    
  simplytestable.controller.action_listener:
    class: SimplyTestable\WorkerBundle\EventListener\BeforeListener    
    arguments:
        logger: "@logger"
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }  
      
  simplytestable.services.taskservice:
    class:   SimplyTestable\WorkerBundle\Services\TaskService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"        
        logger: "@logger"
        stateService: "@simplytestable.services.stateservice"
        taskDriverFactoryService: "@simplytestable.services.taskdriverfactoryservice"
        urlService: "@simplytestable.services.urlservice"
        coreApplicationService: "@simplytestable.services.coreapplicationservice"
        workerService: "@simplytestable.services.workerservice"
        httpClientService: "@simplytestable.services.httpClientService"

  simplytestable.services.tasktypeservice:
    class:   SimplyTestable\WorkerBundle\Services\TaskTypeService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"        
        
  simplytestable.services.taskdriverfactoryservice:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\FactoryService
    arguments:
        drivers: %drivers%  
        container: "@service_container"
        #taskTypeService: "@simplytestable.services.tasktypeservice"
        #stateService: "@simplytestable.services.stateservice"
        #webResourceService: "@simplytestable.services.webresourceservice"        
        #logger: "@logger"
        #webResourceTaskOutputService: "@simplytestable.services.webresourcetaskoutputservice"
        #serializer: "@serializer"
        #timeCachedTaskOutputService: "@simplytestable.services.timecachedtaskoutputservice"
        
  simplytestable.services.resqueQueueService:
    class:   SimplyTestable\WorkerBundle\Services\ResqueQueueService
    arguments:
      queueManager: "@glit_resque.queue_manager"
      logger: "@logger"     
      resqueJobFactoryService: "@simplytestable.services.ResqueJobFactoryService"
      resquePrefix: "%glit_resque.prefix%"      
      
  simplytestable.services.webresourceservice:
    class:   SimplyTestable\WorkerBundle\Services\WebResourceService
    arguments:
        httpClientService: "@simplytestable.services.httpClientService"
        contentTypeWebResourceMap: %content_type_web_resource_map%
        
  simplytestable.services.ResqueJobFactoryService:
    class:  SimplyTestable\WorkerBundle\Services\ResqueJobFactoryService
    arguments:
      jobClassMap: "%resque-job-class-map%"   
      
  simplytestable.services.webresourcetaskoutputservice:
    class:   SimplyTestable\WorkerBundle\Services\WebResourceTaskOutputService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"       
        
  simplytestable.services.timecachedtaskoutputservice:
    class:   SimplyTestable\WorkerBundle\Services\TimeCachedTaskOutputService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"

  simplytestable.services.commandService:
    class:   SimplyTestable\WorkerBundle\Services\CommandService
    arguments:
      container: "@service_container"    
      
  simplytestable.services.memcacheService:
    class:   SimplyTestable\WorkerBundle\Services\MemcacheService     