parameters:
#    simply_testable_worker.example.class: SimplyTestable\WorkerBundle\Example

services:
#    simply_testable_worker.example:
#        class: %simply_testable_worker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
