services:    
  simplytestable.services.httpClientService:
    class:  SimplyTestable\WorkerBundle\Services\TestHttpClientService     
    arguments:
        memcacheService: "@simplytestable.services.memcacheService"        
        
  simplytestable.services.htmlValidatorWrapperService:
    class:  webignition\HtmlValidator\Mock\Wrapper\Wrapper         

  simplytestable.services.cssValidatorWrapperService:
    class:  webignition\CssValidatorWrapper\Mock\Wrapper
    
  simplytestable.services.requestservice:
    class:   SimplyTestable\WorkerBundle\Services\TestRequestService    
    
#  simplytestable.services.webresourceservice:
#    class:   SimplyTestable\WorkerBundle\Services\TestWebResourceService
#    arguments:
#        httpClientService: "@simplytestable.services.httpClientService"
#        contentTypeWebResourceMap: %content_type_web_resource_map%         