#services:
#  simplytestable.services.cssValidatorWrapperService:
#    class:  webignition\CssValidatorWrapper\Mock\Wrapper
#
#  simplytestable.services.nodeJslintWrapperService:
#    class:  webignition\NodeJslint\Wrapper\Mock\Wrapper