imports:
    - { resource: services/task-drivers.yml }
    - { resource: services/resque-job-factory.yml }
    - { resource: services/public.yml }

services:
  SimplyTestable\WorkerBundle\Services\ApplicationConfigurationService:
      arguments:
        - "@=service('kernel').getRootDir()"
        - "@=service('kernel').getCacheDir()"

  SimplyTestable\WorkerBundle\Services\CoreApplicationRouter:
      arguments:
        - '%core_url%'
        - '@SimplyTestable\WorkerBundle\Services\ResourceLocator'
        - '@SimplyTestable\WorkerBundle\Services\ApplicationConfigurationService'

  webignition\HttpHistoryContainer\Container:

  SimplyTestable\WorkerBundle\Services\HttpClientFactory:
    arguments:
      - '%curl_options%'
      - '@SimplyTestable\WorkerBundle\Services\HttpCache'
      - '@webignition\HttpHistoryContainer\Container'

#  GuzzleHttp\Client:
#    factory: ['SimplyTestable\WorkerBundle\Services\HttpClientFactory:create']

  SimplyTestable\WorkerBundle\Services\HttpClientService:
      arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientFactory'

#  webignition\WebResource\Service\Configuration:
#    arguments:
#        $configurationValues:
#          allow-unknown-resource-types: false
#          retry-with-url-encoding-disabled: true
#          content-type-web-resource-map: '%content_type_web_resource_map%'
#
#  webignition\WebResource\Service\Service:
#    class:  webignition\WebResource\Service\Service
#    calls:
#      - [setConfiguration, ['@webignition\WebResource\Service\Configuration']]
  webignition\WebResource\Retriever:
    factory: ['SimplyTestable\WorkerBundle\Services\WebResourceRetrieverFactory', create]

  webignition\HtmlValidator\Wrapper\Wrapper:

  webignition\CssValidatorWrapper\Wrapper:

  webignition\NodeJslint\Wrapper\Wrapper:

  SimplyTestable\WorkerBundle\Services\WorkerService:
    public: true
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@logger'
        - '%secret%'
        - '%hostname%'
        - '@SimplyTestable\WorkerBundle\Services\CoreApplicationRouter'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@SimplyTestable\WorkerBundle\Services\UrlService'

  SimplyTestable\WorkerBundle\Services\TaskService:
    public: true
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@logger'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '@SimplyTestable\WorkerBundle\Services\UrlService'
        - '@SimplyTestable\WorkerBundle\Services\CoreApplicationRouter'
        - '@SimplyTestable\WorkerBundle\Services\WorkerService'
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
    calls:
      - [addTaskDriver, ['html validation', '@SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver']]
      - [addTaskDriver, ['css validation', '@SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver']]
      - [addTaskDriver, ['js static analysis', '@SimplyTestable\WorkerBundle\Services\TaskDriver\JsLintTaskDriver']]
      - [addTaskDriver, ['link integrity', '@SimplyTestable\WorkerBundle\Services\TaskDriver\LinkIntegrityTaskDriver']]
      - [addTaskDriver, ['url discovery', '@SimplyTestable\WorkerBundle\Services\TaskDriver\UrlDiscoveryTaskDriver']]

  SimplyTestable\WorkerBundle\Services\TasksService:
    public: true
    arguments:
      - '@logger'
      - '@SimplyTestable\WorkerBundle\Services\UrlService'
      - '@SimplyTestable\WorkerBundle\Services\CoreApplicationRouter'
      - '@SimplyTestable\WorkerBundle\Services\WorkerService'
      - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
      - '@SimplyTestable\WorkerBundle\Services\TaskService'
    calls:
      - [setWorkerProcessCount, ['%worker_process_count%']]
      - [setMaxTasksRequestFactor, ['%max_tasks_request_factor%']]
