services:
  simplytestable.services.httpClient:
    class:  webignition\Http\Client\Client
    
  simplytestable.services.coreApplicationService:
    class:  SimplyTestable\WorkerBundle\Services\CoreApplicationService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        
  simplytestable.services.stateservice:
    class:  SimplyTestable\WorkerBundle\Services\StateService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"     
        
  simplytestable.services.workerService:
    class:  SimplyTestable\WorkerBundle\Services\WorkerService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"
        logger: "@logger"
        salt: %secret%
        hostname: %hostname%
        coreApplicationService: "@simplytestable.services.coreApplicationService"
        stateService: "@simplytestable.services.stateservice"
        httpClient: "@simplytestable.services.httpClient"
        urlService: "@simplytestable.services.urlService"
        
  simplytestable.services.urlService:
    class:  SimplyTestable\WorkerBundle\Services\UrlService     
    
  simplytestable.services.requestservice:
    class:   SimplyTestable\WorkerBundle\Services\RequestService    
    
  simplytestable.controller.action_listener:
    class: SimplyTestable\WorkerBundle\EventListener\BeforeListener    
    arguments:
        logger: "@logger"
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }  
      
  simplytestable.services.taskservice:
    class:   SimplyTestable\WorkerBundle\Services\TaskService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"        
        logger: "@logger"
        stateService: "@simplytestable.services.stateservice"
        taskDriverFactoryService: "@simplytestable.services.taskdriverfactoryservice"
        urlService: "@simplytestable.services.urlservice"
        coreApplicationService: "@simplytestable.services.coreapplicationservice"
        workerService: "@simplytestable.services.workerservice"
        httpClient: "@simplytestable.services.httpClient"

  simplytestable.services.tasktypeservice:
    class:   SimplyTestable\WorkerBundle\Services\TaskTypeService
    arguments:
        entityManager: "@doctrine.orm.entity_manager"        
        
  simplytestable.services.taskdriverfactoryservice:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\FactoryService
    arguments:
        drivers: %drivers%        
        taskTypeService: "@simplytestable.services.tasktypeservice"
        stateService: "@simplytestable.services.stateservice"
        webResourceService: "@simplytestable.services.webresourceservice"        
        
  simplytestable.services.resqueQueueService:
    class:   SimplyTestable\WorkerBundle\Services\ResqueQueueService
    arguments:
      queueManager: "@glit_resque.queue_manager"
      logger: "@logger"     
      resqueJobFactoryService: "@simplytestable.services.ResqueJobFactoryService"
      resquePrefix: "%glit_resque.prefix%"      
      
  simplytestable.services.webresourceservice:
    class:   SimplyTestable\WorkerBundle\Services\WebResourceService
    arguments:
        httpClient: "@simplytestable.services.httpClient"
        contentTypeWebResourceMap: %content_type_web_resource_map%
        
  simplytestable.services.ResqueJobFactoryService:
    class:  SimplyTestable\ApiBundle\Services\ResqueJobFactoryService
    arguments:
      jobClassMap: "%resque-job-class-map%"        