<?php

namespace SimplyTestable\WorkerBundle\Tests\Services\TaskDriver\CssValidation\HandleMalformedContentType;

class NoSemiColonBetweenTypeAndParameterAndAttributeColonValueTest extends HandleMalformedContentTypeTest {
}