services:
  - redis-server
  - memcache

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  
env:
  global:
    - REPO="webignition/worker.simplytestable.com"
    - CI_HOME=`pwd`/$REPO  
  
before_script:
  # Install memcache extension
  - printf "no\n" | pecl install memcache > /dev/null
  - echo "extension=\"memcache.so\"" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`  
  #- sudo apt-get install php5-memcache
  #- cat /etc/php5/conf.d/memcache.ini
  #- cat /etc/php5/cli/conf.d/memcache.ini
  #- "php -i | grep memcache"  
  #- "php -r 'new \Memcache;'"  
  
  # Install the W3C CSS validator
  - sudo apt-get install ant cvs openjdk-7-jdk
  - sudo mkdir /usr/share/css-validator
  - cd /usr/share/css-validator
  - sudo CVSROOT=:pserver:anonymous:anonymous@dev.w3.org:/sources/public cvs -q checkout 2002/css-validator
  - cd 2002/css-validator/
  - sudo ant -q jar
  - cd $CI_HOME
  
  # Install nodejs and node-jslint
  - sudo apt-get install nodejs npm
  - sudo ln -s /usr/bin/node /usr/bin/nodejs
  - ls -la /usr/bin/node
  - ls -la /usr/bin/nodejs
  - sudo mkdir /usr/share/node-jslint && cd /usr/share/node-jslint && sudo npm install jslint && sudo npm install jslint
  - cd $CI_HOME
  
  # Test node-jslint
  - /usr/bin/nodejs /usr/share/node-jslint/node_modules/jslint/bin/jslint.js travis-ci/sample.js
  
  # Install composer for dependency management
  - wget http://getcomposer.org/composer.phar 
  
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json  
  
  # Build!
  #- mkdir app/cache/test  
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - cp app/config/security_credentials.yml.dist app/config/security_credentials.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - cp src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml.dist src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml
  - php composer.phar install
  - php app/console doctrine:database:create
  - php app/console doctrine:migrations:migrate --no-interaction
  
  # Update /etc/hosts for html validator
  - echo "5.9.84.201 html-validator.worker.simplytestable.com" | sudo tee --append /etc/hosts
  
script:
  - phpunit -c app --group standard
  - phpunit -c app --group integration-standard-travis
  - phpunit -c app --group integration-html-validation-travis
  - phpunit -c app --group integration-css-validation-travis
  - phpunit -c app --group integration-js-static-analysis-travis
  
after_failure:
  #- cat /home/travis/build/webignition/worker.simplytestable.com/app/logs/test.log | grep "response fixture path"
  #- cat /home/travis/build/webignition/worker.simplytestable.com/app/logs/test.log | grep "TaskService::reportCompletion"
  
notifications:
  irc:
    - "irc.freenode.org#simplytestable"
    