sudo: false
services:
  - redis-server
  - memcache

env:
  - APP_ENV=test DATABASE_URL=mysql://root:@127.0.0.1:3306/myapp_test APP_SECRET=Secret! CORE_URL=http://app.simplytestable.com HTML_VALIDATOR_PATH=/usr/local/validator/cgi-bin/check CSS_VALIDATOR_JAR_PATH=/usr/share/css-validator/2002/css-validator/css-validator.jar NODE_PATH=/usr/bin/node NODE_JSLINT_PATH=/usr/share/node-jslint/node_modules/jslint/bin/jslint.js HOSTNAME=worker.simplytestable.com WORKER_PROCESS_COUNT=5 MAX_TASKS_REQUEST_FACTOR=2 RESQUE_PREFIX=worker

language: php
php:
  - 7.2

before_install:
  - composer self-update
  - cp .travis.composer.config.json ~/.composer/config.json
  - rm phpunit.xml.dist
  - mv phpunit.travis-ci.xml phpunit.xml.dist
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'CREATE DATABASE myapp_test;'
  - chmod +x ./bin/console

install:
  - composer install
  - php bin/console doctrine:migrations:migrate --no-interaction
  - php bin/console doctrine:fixtures:load --append
  - composer config --global process-timeout 2000

script:
  - composer ci
