language: php
php:
  - 5.3
  - 5.4
  
before_script:  
  # Installing phing
  #- git clone https://github.com/phingofficial/phing.git build/phing
  
  # Installing pecl_http module
  - printf "\n\n\n\n" | pecl -q install pecl_http
  - echo "extension=http.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`  
  
  # Install composer for dependency management
  - wget http://getcomposer.org/composer.phar 
  
  # Build!
  #- mkdir app/cache/test  
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - cp src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml.dist src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml
  - php composer.phar install
  - php app/console doctrine:database:create
  - php app/console doctrine:migrations:migrate --no-interaction
  
script:
  - phpunit -c app
  
  
after_script:
  - cat app/logs/test.log