sudo: false
services:
  - redis-server
  - memcache

env:
  - APP_ENV=test

language: php
php:
  - 7.2

before_install:
  - composer self-update
  - cp .travis.composer.config.json ~/.composer/config.json
  - rm phpunit.xml.dist
  - mv phpunit.travis-ci.xml phpunit.xml.dist
  - mv .env.travis-ci .env
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'CREATE DATABASE myapp_test;'
  - chmod +x ./bin/console

install:
  - composer install
  - php bin/console doctrine:migrations:migrate --no-interaction
  - php bin/console doctrine:fixtures:load --append
  - composer config --global process-timeout 2000

script:
  - composer ci
