services:
  - redis-server

language: php
php:
  - 5.3
  - 5.4
  
before_script:  
  # Installing phing
  #- git clone https://github.com/phingofficial/phing.git build/phing
  
  # Installing pecl_http module
  - printf "\n\n\n\n" | pecl -q install pecl_http
  #- echo "extension=http.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`  
  
  # Install composer for dependency management
  - wget http://getcomposer.org/composer.phar 
  
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json  
  
  # Build!
  #- mkdir app/cache/test  
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - cp app/config/security_credentials.yml.dist app/config/security_credentials.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - cp src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml.dist src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml
  - php composer.phar install
  - php app/console doctrine:database:create
  - php app/console doctrine:migrations:migrate --no-interaction
  
script:
  - phpunit -c app
  
after_failure:
  - cat /home/travis/build/webignition/worker.simplytestable.com/app/logs/test.log | grep "response fixture path"
  - cat /home/travis/build/webignition/worker.simplytestable.com/app/logs/test.log | grep "TaskService::reportCompletion"
  
notifications:
  irc:
    - "irc.freenode.org#simplytestable"  