services:
  - redis-server
  - memcache

language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
env:
  global:
    - REPO="webignition/worker.simplytestable.com"
    - CI_HOME=`pwd`/$REPO  
  
before_script:
  # Install memcache extension
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  #- php -r 'new \Memcache;'

  # Install composer for dependency management
  - wget http://getcomposer.org/composer.phar 
  
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json  
  
  # Build!
  #- mkdir app/cache/test  
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - cp app/config/security_credentials.yml.dist app/config/security_credentials.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - cp src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml.dist src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml
  - php composer.phar install
  - php app/console doctrine:database:create
  - php app/console doctrine:migrations:migrate --no-interaction
  - php app/console doctrine:fixtures:load --append  
  
  # Update /etc/hosts for html validator
  #- echo "5.9.84.201 html-validator.worker.simplytestable.com" | sudo tee --append /etc/hosts
  
script:
  - phpunit -c app
  #- phpunit -c app --group standard
  #- phpunit -c app --group standard
  #- phpunit -c app --group integration-standard-travis
  #- phpunit -c app --group integration-html-validation-travis
  #- phpunit -c app --group integration-css-validation-travis
  #- phpunit -c app --group integration-js-static-analysis-travis
  
after_failure:
  #- cat /home/travis/build/webignition/worker.simplytestable.com/app/logs/test.log | grep "response fixture path"
  #- cat /home/travis/build/webignition/worker.simplytestable.com/app/logs/test.log | grep "TaskService::reportCompletion"
  
notifications:
  irc:
    - "irc.freenode.org#simplytestable"
    
matrix:
  allow_failures:
    - php: hhvm      