language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
before_install:
  - composer self-update
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  
install: 
  - composer install

before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  #- php -r 'new \Memcache;'

script:
  - phpunit -c app

notifications:
  irc:
    - "irc.freenode.org#simplytestable"

matrix:
  allow_failures:
    - php: hhvm