sudo: false
services:
  - redis-server
  - memcache

language: php
php:
  - 5.6
  - 7
  - 7.1

before_install:
  - composer self-update
  - cp .travis.composer.config.json ~/.composer/config.json
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - cp app/config/security_credentials.yml.dist app/config/security_credentials.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - cp src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml.dist src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:migrations:migrate --no-interaction
  - php app/console doctrine:fixtures:load --append
  - composer config --global process-timeout 2000

script:
  - composer test
