sudo: false
services:
  - redis-server
  - memcache

env:
  - SYMFONY_ENV=test

language: php
php:
  - 7.2

before_install:
  - composer self-update
  - cp .travis.composer.config.json ~/.composer/config.json
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - cp src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml.dist src/SimplyTestable/WorkerBundle/Resources/config/parameters.yml
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'CREATE DATABASE myapp_test;'
  - chmod +x ./bin/console

install:
  - composer install
  - php bin/console doctrine:migrations:migrate --no-interaction
  - php bin/console doctrine:fixtures:load --append
  - composer config --global process-timeout 2000

script:
  - composer ci
