# Define all commands as public to allow them to be retrieved from the container in functional tests
services:
  SimplyTestable\WorkerBundle\Command\:
      resource: '../../../Command'
      public: true
      autowire: true
      autoconfigure: true
      tags: ['console.command']
