# Services that need to be public to allow them to be retrieved from the container in functional tests
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  GuzzleHttp\Client:
    factory: 'SimplyTestable\WorkerBundle\Services\HttpClientService:getHttpClient'

  SimplyTestable\WorkerBundle\Services\ApplicationConfigurationService:
      arguments:
        - "@=service('kernel').getRootDir()"
        - "@=service('kernel').getCacheDir()"

  SimplyTestable\WorkerBundle\Services\CoreApplicationRouter:
      arguments:
        - '%core_url%'
        - '@SimplyTestable\WorkerBundle\Services\ResourceLocator'
        - '@SimplyTestable\WorkerBundle\Services\ApplicationConfigurationService'

  SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver:
    arguments:
      - '@SimplyTestable\WorkerBundle\Services\StateService'
      - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
      - '@SimplyTestable\WorkerBundle\Services\HttpClientConfigurationService'
      - '@webignition\WebResource\Retriever'
      - '@webignition\HtmlValidator\Wrapper\Wrapper'
      - '%html-validator-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidatorWrapperConfigurationFactory:
    arguments:
      - '%css-validator-jar-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver:

  SimplyTestable\WorkerBundle\Services\TaskDriver\NodeJsLintWrapperConfigurationFactory:
    arguments:
      - '%node-path%'
      - '%node-jslint-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\JsLintTaskDriver:

  SimplyTestable\WorkerBundle\Services\TaskDriver\LinkCheckerConfigurationFactory:
    arguments:
      - '%link_integrity_user_agents%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\LinkIntegrityTaskDriver:

  SimplyTestable\WorkerBundle\Services\TaskDriver\UrlDiscoveryTaskDriver:

  SimplyTestable\WorkerBundle\Services\ResourceLocator:

  SimplyTestable\WorkerBundle\Services\MemcachedService:

  SimplyTestable\WorkerBundle\Services\Resque\QueueService:

  SimplyTestable\WorkerBundle\Services\TaskTypeService:

  SimplyTestable\WorkerBundle\Services\StateService:

  SimplyTestable\WorkerBundle\Services\HttpCache:

  SimplyTestable\WorkerBundle\Services\TaskFactory:

  SimplyTestable\WorkerBundle\Services\Request\Factory\Task\CreateRequestCollectionFactory:

  SimplyTestable\WorkerBundle\Services\Request\Factory\Task\CancelRequestFactory:

  SimplyTestable\WorkerBundle\Services\Request\Factory\Task\CancelRequestCollectionFactory:

  SimplyTestable\WorkerBundle\Services\Request\Factory\VerifyRequestFactory:

  webignition\CssValidatorWrapper\Wrapper:

  webignition\NodeJslint\Wrapper\Wrapper:

  SimplyTestable\WorkerBundle\Services\HttpClientConfigurationService:
