# Services that need to be public to allow them to be retrieved from the container in functional tests
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  SimplyTestable\WorkerBundle\Services\ApplicationConfigurationService:
      arguments:
        - "@=service('kernel').getRootDir()"
        - "@=service('kernel').getCacheDir()"

#  SimplyTestable\WorkerBundle\Services\HttpClientService:
#      arguments:
#        - '@SimplyTestable\WorkerBundle\Services\HttpCache'
#        - '%curl_options%'
#
#  webignition\WebResource\Service\Service:
#    class:  webignition\WebResource\Service\Service
#    calls:
#      - [setConfiguration, ['@webignition\WebResource\Service\Configuration']]

  SimplyTestable\WorkerBundle\Services\CoreApplicationRouter:
      arguments:
        - '%core_url%'
        - '@SimplyTestable\WorkerBundle\Services\ResourceLocator'
        - '@SimplyTestable\WorkerBundle\Services\ApplicationConfigurationService'

  SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver:
    arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@webignition\WebResource\Retriever'
        - '@webignition\HtmlValidator\Wrapper\Wrapper'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '%html-validator-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver
    arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@webignition\WebResource\Retriever'
        - '@webignition\CssValidatorWrapper\Wrapper'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '%css-validator-jar-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\JsLintTaskDriver:
    arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@webignition\WebResource\Retriever'
        - '@webignition\NodeJslint\Wrapper\Wrapper'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '@logger'
        - '%node-path%'
        - '%node-jslint-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\LinkIntegrityTaskDriver:
    arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@webignition\WebResource\Retriever'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '%link_integrity_user_agents%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\UrlDiscoveryTaskDriver:
    arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@webignition\WebResource\Retriever'
        - '@SimplyTestable\WorkerBundle\Services\StateService'

  SimplyTestable\WorkerBundle\Services\ResourceLocator:

  SimplyTestable\WorkerBundle\Services\MemcachedService:

  SimplyTestable\WorkerBundle\Services\Resque\QueueService:

  SimplyTestable\WorkerBundle\Services\TaskTypeService:

  SimplyTestable\WorkerBundle\Services\StateService:

  SimplyTestable\WorkerBundle\Services\HttpCache:

  SimplyTestable\WorkerBundle\Services\TaskFactory:

  SimplyTestable\WorkerBundle\Services\Request\Factory\Task\CreateRequestCollectionFactory:

  SimplyTestable\WorkerBundle\Services\Request\Factory\Task\CancelRequestFactory:

  SimplyTestable\WorkerBundle\Services\Request\Factory\Task\CancelRequestCollectionFactory:

  SimplyTestable\WorkerBundle\Services\Request\Factory\VerifyRequestFactory:

  webignition\CssValidatorWrapper\Wrapper:

  webignition\NodeJslint\Wrapper\Wrapper:

  webignition\HttpHistoryContainer\Container:
