# Test-specific services that extend regular services to allow functionality to be mocked/controlled during tests
services:
  SimplyTestable\WorkerBundle\Services\TaskService:
    class:   Tests\WorkerBundle\Services\TestTaskService
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@logger'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '@SimplyTestable\WorkerBundle\Services\UrlService'
        - '@SimplyTestable\WorkerBundle\Services\CoreApplicationRouter'
        - '@SimplyTestable\WorkerBundle\Services\WorkerService'
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
    calls:
      - [addTaskDriver, ['html validation', '@SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver']]
      - [addTaskDriver, ['css validation', '@SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver']]
      - [addTaskDriver, ['js static analysis', '@SimplyTestable\WorkerBundle\Services\TaskDriver\JsLintTaskDriver']]
      - [addTaskDriver, ['link integrity', '@SimplyTestable\WorkerBundle\Services\TaskDriver\LinkIntegrityTaskDriver']]
      - [addTaskDriver, ['url discovery', '@SimplyTestable\WorkerBundle\Services\TaskDriver\UrlDiscoveryTaskDriver']]

  SimplyTestable\WorkerBundle\Services\TasksService:
    class:   Tests\WorkerBundle\Services\TestTasksService
    arguments:
      - '@logger'
      - '@SimplyTestable\WorkerBundle\Services\UrlService'
      - '@SimplyTestable\WorkerBundle\Services\CoreApplicationRouter'
      - '@SimplyTestable\WorkerBundle\Services\WorkerService'
      - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
      - '@SimplyTestable\WorkerBundle\Services\TaskService'
    calls:
      - [setWorkerProcessCount, ['%worker_process_count%']]
      - [setMaxTasksRequestFactor, ['%max_tasks_request_factor%']]

  SimplyTestable\WorkerBundle\Services\WorkerService:
    class:   Tests\WorkerBundle\Services\TestWorkerService
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@logger'
        - '%secret%'
        - '%hostname%'
        - '@SimplyTestable\WorkerBundle\Services\CoreApplicationRouter'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@SimplyTestable\WorkerBundle\Services\UrlService'
