# Test-specific services that extend regular services to allow functionality to be mocked/controlled during tests
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Tests\WorkerBundle\Services\HttpMockHandler:
    public: true

  SimplyTestable\WorkerBundle\Services\HttpHandlerStackFactory:
    arguments:
      - '@webignition\Guzzle\Middleware\HttpAuthentication\HttpAuthenticationMiddleware'
      - '@webignition\Guzzle\Middleware\RequestHeaders\RequestHeadersMiddleware'
      - '@webignition\HttpHistoryContainer\Container'
      - '@Kevinrob\GuzzleCache\CacheMiddleware'
      - '@Tests\WorkerBundle\Services\HttpMockHandler'

  SimplyTestable\WorkerBundle\Services\TasksService:
    class:   Tests\WorkerBundle\Services\TestTasksService
    arguments:
      - '@logger'
      - '@SimplyTestable\WorkerBundle\Services\WorkerService'
      - '@SimplyTestable\WorkerBundle\Services\TaskService'
      - '@SimplyTestable\WorkerBundle\Services\CoreApplicationHttpClient'
    calls:
      - [setWorkerProcessCount, ['%worker_process_count%']]
      - [setMaxTasksRequestFactor, ['%max_tasks_request_factor%']]

  SimplyTestable\WorkerBundle\Services\WorkerService:
    class:   Tests\WorkerBundle\Services\TestWorkerService
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@logger'
        - '%secret%'
        - '%hostname%'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '@SimplyTestable\WorkerBundle\Services\CoreApplicationHttpClient'
