imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

resque:
    prefix: '%bcc_resque_prefix%'                # optional prefix to separate Resque data per site/app
