imports:
    - { resource: config_dev.yml }
    - { resource: "@SimplyTestableWorkerBundle/Resources/config/parameters_test.yml" }    
    - { resource: "@SimplyTestableWorkerBundle/Resources/config/services_test.yml" }      

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
  dbal:
    connections:
      default:
        driver: pdo_sqlite
        path: /run/shm/worker.simplytestable.com.db
        
monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info        
