status:
    path:  /
    defaults: { _controller: SimplyTestable\AppBundle\Controller\StatusController::indexAction, _format: json }

verify:
    path:  /verify/
    defaults: { _controller: SimplyTestable\AppBundle\Controller\VerifyController::indexAction, _format: json  }

task_create_collection:
    path:  /task/create/collection/
    defaults: { _controller: SimplyTestable\AppBundle\Controller\TaskController::createCollectionAction, _format: json  }

task_cancel:
    path:  /task/cancel/
    defaults: { _controller: SimplyTestable\AppBundle\Controller\TaskController::cancelAction, _format: json  }

task_cancel_collection:
    path:  /task/cancel/collection/
    defaults: { _controller: SimplyTestable\AppBundle\Controller\TaskController::cancelCollectionAction, _format: json  }

disable_readonly:
    path: /maintenance/disable-read-only/
    defaults: { _controller: SimplyTestable\AppBundle\Controller\MaintenanceController::disableReadOnlyAction, _format: json n }

enable_readonly:
    path: /maintenance/enable-read-only/
    defaults: { _controller: SimplyTestable\AppBundle\Controller\MaintenanceController::enableReadOnlyAction, _format: json  }

leave_readonly:
    path: /maintenance/leave-read-only/
    defaults: { _controller: SimplyTestable\AppBundle\Controller\MaintenanceController::leaveReadOnlyAction, _format: json  }

task_perform_enqueue:
    path: /maintenance/task-perform-enqueue/
    defaults: { _controller: SimplyTestable\AppBundle\Controller\MaintenanceController::taskPerformEnqueueAction, _format: json  }

tasks_notify:
    path: /tasks/notify/
    defaults: { _controller: SimplyTestable\AppBundle\Controller\TasksController::notifyAction, _format: json  }
