imports:
    - { resource: security_credentials.yml }

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        main:
            pattern: ^/
            anonymous: ~
            form_login: false
            http_basic:
                realm: "Simply Testable Core Application"

            logout_on_user_change: true

    access_control:
        - { path: ^/maintenance/, role: ROLE_ADMIN }
