services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SimplyTestable\WorkerBundle\Services\WorkerService:
    class:   Tests\WorkerBundle\Services\TestWorkerService
    arguments:
      $salt: '%secret%'
      $hostname: '%hostname%'

  SimplyTestable\WorkerBundle\Services\TasksService:
    class:   Tests\WorkerBundle\Services\TestTasksService
    calls:
      - [setWorkerProcessCount, ['%worker_process_count%']]
      - [setMaxTasksRequestFactor, ['%max_tasks_request_factor%']]

  Tests\WorkerBundle\Services\HttpMockHandler:

  SimplyTestable\WorkerBundle\Services\HttpHandlerStackFactory:
    arguments:
      - '@webignition\Guzzle\Middleware\HttpAuthentication\HttpAuthenticationMiddleware'
      - '@webignition\Guzzle\Middleware\RequestHeaders\RequestHeadersMiddleware'
      - '@webignition\HttpHistoryContainer\Container'
      - '@Kevinrob\GuzzleCache\CacheMiddleware'
      - '@Tests\WorkerBundle\Services\HttpMockHandler'