services:
  simplytestable.command.maintenance.disablereadonly:
    class: SimplyTestable\WorkerBundle\Command\Maintenance\DisableReadOnlyCommand
    arguments:
        workerService: "@simplytestable.services.workerservice"
    tags:
      - { name: console.command }

  simplytestable.command.maintenance.enablereadonly:
    class: SimplyTestable\WorkerBundle\Command\Maintenance\EnableReadOnlyCommand
    arguments:
        workerService: "@simplytestable.services.workerservice"
    tags:
      - { name: console.command }

  simplytestable.command.task.perform:
    class:   SimplyTestable\WorkerBundle\Command\Task\PerformCommand
    arguments:
        logger: "@logger"
        taskService: "@simplytestable.services.taskservice"
        workerService: "@simplytestable.services.workerservice"
        resqueQueueService: "@simplytestable.services.resque.queueservice"
        resqueJobFactoryService: "@simplytestable.services.resque.jobfactoryservice"
    tags:
      - { name: console.command }
