services:
  simplytestable.command.task.perform:
    class:   SimplyTestable\WorkerBundle\Command\Task\PerformCommand
    arguments:
        logger: "@logger"
        taskService: "@simplytestable.services.taskservice"
        workerService: "@simplytestable.services.workerservice"
        resqueQueueService: "@simplytestable.services.resque.queueservice"
        resqueJobFactoryService: "@simplytestable.services.resque.jobfactoryservice"
    tags:
      - { name: console.command }
