services:
  webignition\Guzzle\Middleware\HttpAuthentication\HttpAuthenticationMiddleware:

  webignition\Guzzle\Middleware\RequestHeaders\RequestHeadersMiddleware:

  GuzzleHttp\HandlerStack:
    factory: 'SimplyTestable\WorkerBundle\Services\HttpHandlerStackFactory:create'

  Kevinrob\GuzzleCache\CacheMiddleware:
    factory: 'SimplyTestable\WorkerBundle\Services\HttpCacheMiddlewareFactory:create'

  webignition\HttpHistoryContainer\Container:

  SimplyTestable\WorkerBundle\Services\HttpClientService:
    arguments:
      - '%curl_options%'
      - '@GuzzleHttp\HandlerStack'
      - '@SimplyTestable\WorkerBundle\Services\HttpRetryMiddleware'
      - '@webignition\Guzzle\Middleware\HttpAuthentication\HttpAuthenticationMiddleware'
      - '@webignition\Guzzle\Middleware\RequestHeaders\RequestHeadersMiddleware'

  GuzzleHttp\Client:
    factory: 'SimplyTestable\WorkerBundle\Services\HttpClientService:getHttpClient'
