services:
  SimplyTestable\WorkerBundle\Services\FooHttpClientService:
    arguments:
      - '%curl_options%'
      - '@SimplyTestable\WorkerBundle\Services\HttpCache'

  GuzzleHttp\Client:
    factory: 'SimplyTestable\WorkerBundle\Services\FooHttpClientService:getHttpClient'
