# Services that need to be public to allow them to be retrieved from the container
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  SimplyTestable\WorkerBundle\Services\Resque\QueueService:

  SimplyTestable\WorkerBundle\Command\Task\PerformCommand:

  SimplyTestable\WorkerBundle\Command\Task\ReportCompletionCommand:

  SimplyTestable\WorkerBundle\Command\Tasks\Request:

  SimplyTestable\WorkerBundle\Command\Tasks\RequestCommand:
