services:
  webignition\ResqueJobFactory\ResqueJobFactory:
    public: true
    arguments:
        $queues:
          task-perform:
            queue: task-perform
            jobClassName: SimplyTestable\WorkerBundle\Resque\Job\TaskPerformJob
            requiredArgs:
              - id
          task-report-completion:
            queue: task-report-completion
            jobClassName: SimplyTestable\WorkerBundle\Resque\Job\TaskReportCompletionJob
            requiredArgs:
              - id
          tasks-request:
            queue: tasks-request
            jobClassName: SimplyTestable\WorkerBundle\Resque\Job\TasksRequestJob
