services:
  SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver:
    arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@simplytestable.services.webresourceservice'
        - '@simplytestable.services.htmlvalidatorwrapper'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '%html-validator-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver
    arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@simplytestable.services.webresourceservice'
        - '@simplytestable.services.cssvalidatorwrapper'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '%css-validator-jar-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\JsLintTaskDriver:
    arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@simplytestable.services.webresourceservice'
        - '@simplytestable.services.nodejslintwrapper'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '@logger'
        - '%node-path%'
        - '%node-jslint-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\LinkIntegrityTaskDriver:
    arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@simplytestable.services.webresourceservice'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
        - '%link_integrity_user_agents%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\UrlDiscoveryTaskDriver:
    arguments:
        - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
        - '@simplytestable.services.webresourceservice'
        - '@SimplyTestable\WorkerBundle\Services\StateService'
