services:
  SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver:
    arguments:
      - '@SimplyTestable\WorkerBundle\Services\StateService'
      - '@SimplyTestable\WorkerBundle\Services\HttpClientService'
      - '@SimplyTestable\WorkerBundle\Services\HttpClientConfigurationService'
      - '@webignition\WebResource\Retriever'
      - '@webignition\HttpHistoryContainer\Container'
      - '@webignition\HtmlValidator\Wrapper\Wrapper'
      - '%html-validator-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidatorWrapperConfigurationFactory:
    arguments:
      - '%css-validator-jar-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\NodeJsLintWrapperConfigurationFactory:
    arguments:
      - '%node-path%'
      - '%node-jslint-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\LinkCheckerConfigurationFactory:
    arguments:
      - '%link_integrity_user_agents%'
