services:
  SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver:
    arguments:
      - '@SimplyTestable\WorkerBundle\Services\StateService'
      - '@SimplyTestable\WorkerBundle\Services\FooHttpClientService'
      - '@webignition\WebResource\Retriever'
      - '@webignition\HtmlValidator\Wrapper\Wrapper'
      - '%html-validator-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver
    arguments:
      - '@SimplyTestable\WorkerBundle\Services\StateService'
      - '@SimplyTestable\WorkerBundle\Services\FooHttpClientService'
      - '@webignition\WebResource\Retriever'
      - '@webignition\CssValidatorWrapper\Wrapper'
      - '%css-validator-jar-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\JsLintTaskDriver:
    arguments:
      - '@SimplyTestable\WorkerBundle\Services\StateService'
      - '@SimplyTestable\WorkerBundle\Services\FooHttpClientService'
      - '@webignition\WebResource\Retriever'
      - '@logger'
      - '@webignition\NodeJslint\Wrapper\Wrapper'
      - '%node-path%'
      - '%node-jslint-path%'

  SimplyTestable\WorkerBundle\Services\TaskDriver\LinkIntegrityTaskDriver:
    arguments:
      - '@SimplyTestable\WorkerBundle\Services\StateService'
      - '@SimplyTestable\WorkerBundle\Services\FooHttpClientService'
      - '@webignition\WebResource\Retriever'
      - '%link_integrity_user_agents%'
