services:
  simplytestable.services.taskdriver.htmlvalidation:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\HtmlValidationTaskDriver
    arguments:
        - '@simplytestable.services.httpclientservice'
        - '@simplytestable.services.webResourceService'
        - '@simplytestable.services.htmlValidatorWrapperService'
        - '@simplytestable.services.stateService'
        - '%html-validator-path%'

  simplytestable.services.taskdriver.cssvalidation:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\CssValidationTaskDriver
    arguments:
        - '@simplytestable.services.httpclientservice'
        - '@simplytestable.services.webResourceService'
        - '@simplytestable.services.cssValidatorWrapperService'
        - '@simplytestable.services.stateService'
        - '%css-validator-jar-path%'

  simplytestable.services.taskdriver.jslint:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\JsLintTaskDriver
    arguments:
        - '@simplytestable.services.httpclientservice'
        - '@simplytestable.services.webResourceService'
        - '@simplytestable.services.nodeJslintWrapperService'
        - '@simplytestable.services.stateService'
        - '@logger'
        - '%node-path%'
        - '%node-jslint-path%'

  simplytestable.services.taskdriver.linkintegrity:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\LinkIntegrityTaskDriver
    arguments:
        - '@simplytestable.services.httpclientservice'
        - '@simplytestable.services.webResourceService'
        - '@simplytestable.services.stateService'
        - '%link_integrity_user_agents%'

  simplytestable.services.taskdriver.urldiscovery:
    class:   SimplyTestable\WorkerBundle\Services\TaskDriver\UrlDiscoveryTaskDriver
    arguments:
        - '@simplytestable.services.httpclientservice'
        - '@simplytestable.services.webResourceService'
        - '@simplytestable.services.stateService'
