<?php

namespace Application\Migrations;

use SimplyTestable\BaseMigrationsBundle\Migration\BaseMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140326210847_drop_WebResourceTaskOutput extends BaseMigration
{
    public function up(Schema $schema)
    {
        $this->statements['mysql'] = array(
            "DROP TABLE TimeCachedTaskOutput"
        );
        
        $this->statements['sqlite'] = array(
            "DROP TABLE TimeCachedTaskOutput"
        ); 
        
        parent::up($schema);
    }
   

    public function down(Schema $schema)
    {
        $this->statements['mysql'] = array(
            "CREATE TABLE WebResourceTaskOutput (
                id INT AUTO_INCREMENT NOT NULL,
                hash VARCHAR(255) NOT NULL,
                output LONGTEXT NOT NULL,
                errorCount INT NOT NULL,
                INDEX hash_index (hash),
                PRIMARY KEY(id))
             DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB"
        );
        
        $this->statements['sqlite'] = array(
            "CREATE TABLE WebResourceTaskOutput (
                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                hash VARCHAR(255) NOT NULL COLLATE NOCASE,
                output LONGTEXT NOT NULL COLLATE NOCASE,
                errorCount INT NOT NULL)",
            "CREATE INDEX hash_index ON WebResourceTaskOutput (hash)"
        );   
        
        parent::down($schema);
    }    
    
//    public function up(Schema $schema)
//    {
//        // this up() migration is autogenerated, please modify it to your needs
//        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
//        
//        $this->addSql("DROP TABLE WebResourceTaskOutput");
//    }
//
//    public function down(Schema $schema)
//    {
//        // this down() migration is autogenerated, please modify it to your needs
//        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
//        
//        $this->addSql("CREATE TABLE WebResourceTaskOutput (id INT AUTO_INCREMENT NOT NULL, state_id INT DEFAULT NULL, hash VARCHAR(255) NOT NULL, output LONGTEXT NOT NULL, errorCount INT NOT NULL, INDEX hash_index (hash), INDEX IDX_9AEBC03A5D83CC1 (state_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
//        $this->addSql("ALTER TABLE WebResourceTaskOutput ADD CONSTRAINT FK_9AEBC03A5D83CC1 FOREIGN KEY (state_id) REFERENCES State (id)");
//    }
}
