status:
    path:  /
    defaults: { _controller: App\Controller\StatusController::indexAction, _format: json }

verify:
    path:  /verify/
    defaults: { _controller: App\Controller\VerifyController::indexAction, _format: json  }

task_create_collection:
    path:  /task/create/collection/
    defaults: { _controller: App\Controller\TaskController::createCollectionAction, _format: json  }

task_cancel:
    path:  /task/cancel/
    defaults: { _controller: App\Controller\TaskController::cancelAction, _format: json  }

task_cancel_collection:
    path:  /task/cancel/collection/
    defaults: { _controller: App\Controller\TaskController::cancelCollectionAction, _format: json  }

tasks_notify:
    path: /tasks/notify/
    defaults: { _controller: App\Controller\TasksController::notifyAction, _format: json  }
