services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Services\TasksService:
    class:   App\Tests\Services\TestTasksService
    calls:
      - [setWorkerProcessCount, ['%env(WORKER_PROCESS_COUNT)%']]
      - [setMaxTasksRequestFactor, ['%env(MAX_TASKS_REQUEST_FACTOR)%']]

  App\Tests\Services\HttpMockHandler:

  App\Services\HttpHandlerStackFactory:
    arguments:
      - '@webignition\Guzzle\Middleware\HttpAuthentication\HttpAuthenticationMiddleware'
      - '@webignition\Guzzle\Middleware\RequestHeaders\RequestHeadersMiddleware'
      - '@webignition\HttpHistoryContainer\Container'
      - '@Kevinrob\GuzzleCache\CacheMiddleware'
      - '@App\Tests\Services\HttpMockHandler'

  App\Tests\Services\TestTaskFactory:
    public: true

  App\Tests\Services\ContentTypeFactory:
    public: true

  App\Services\UrlSourceMapFactory:
    public: true
