services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Tests\Services\HttpMockHandler:

  App\Services\HttpHandlerStackFactory:
    arguments:
      - '@webignition\Guzzle\Middleware\HttpAuthentication\HttpAuthenticationMiddleware'
      - '@webignition\Guzzle\Middleware\RequestHeaders\RequestHeadersMiddleware'
      - '@webignition\HttpHistoryContainer\Container'
      - '@webignition\Guzzle\Middleware\ResponseLocationUriFixer\Factory'
      - '@Kevinrob\GuzzleCache\CacheMiddleware'
      - '@App\Tests\Services\HttpMockHandler'

  App\Tests\Services\TestTaskFactory:
    public: true

  App\Tests\Services\ContentTypeFactory:
    public: true

  App\Tests\Services\TaskSourceContentsLoader:
    public: true

  App\Services\UrlSourceMapFactory:
    public: true

  App\Services\CssValidatorOutputParserConfigurationFactory:
    public: true

  App\Services\CssValidatorErrorFactory:
    public: true

  App\Services\WebPageTaskCssUrlFinder:
    public: true

  App\Tests\Services\TaskTypeRetriever:
    public: true

  App\Services\MemcachedService:
    public: true
