services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Services\TasksService:
    class:   App\Tests\Services\TestTasksService
    calls:
      - [setWorkerProcessCount, ['%env(WORKER_PROCESS_COUNT)%']]
      - [setMaxTasksRequestFactor, ['%env(MAX_TASKS_REQUEST_FACTOR)%']]

  App\Tests\Services\HttpMockHandler:

  App\Services\HttpHandlerStackFactory:
    arguments:
      - '@webignition\Guzzle\Middleware\HttpAuthentication\HttpAuthenticationMiddleware'
      - '@webignition\Guzzle\Middleware\RequestHeaders\RequestHeadersMiddleware'
      - '@webignition\HttpHistoryContainer\Container'
      - '@Kevinrob\GuzzleCache\CacheMiddleware'
      - '@App\Tests\Services\HttpMockHandler'

  App\Tests\Services\TestTaskFactory:
    public: true

  App\Tests\Services\ContentTypeFactory:
    public: true

  App\Services\ApplicationState:
    public: true
    arguments:
      $stateResourcePath: '%kernel.project_dir%/config/state/%kernel.environment%'

  App\Services\SourceFactory:
    public: true

  app.services.web-resource-retriever.web-page:
    public: true
    class: webignition\WebResource\Retriever
    arguments:
      $httpClient: '@GuzzleHttp\Client'
      $allowedContentTypes:
        - 'text/html'
        - 'application/xhtml+xml'
      $allowUnknownResourceTypes: false

  App\Services\CachedResourceManager:
    public: true

  App\Services\TaskTypePreparer\WebPageTaskSourcePreparer:
    tags:
      - { name: kernel.event_listener, event: task.prepare, priority: 100 }
    public: true
